### ISSUE TITLE
How to configure other storage configs when in DB-less?

### ISSUE THREAD

**Issue by Videl** [fffonion/lua-resty-acme#73]
Hello,

The documentation says that we can configure other storage, and points to this part:
https://docs.konghq.com/hub/kong-inc/acme/#storage-config

But I'm not sure how I'm supposed to write a **record** type in DB-less (yaml format).
I tried this:

```
plugins:
- name: acme
  config:
    account_email: mymail
    cert_type: ecc
    domains: ["*.mydomain"]
    tos_accepted: true
    storage: vault
    storage_config:
      host: myvault
      port: 443
      token: mytoken
      kv_path: mypath
```
but I got this parsing error:

```
2022/08/01 14:29:18 [error] 169559#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /etc/kong/kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'storage_config':
        in 'kv_path': unknown field
        in 'token': unknown field
        in 'host': unknown field
        in 'port': unknown field
```

Did I miss some part of the documentation?

**Comment by fffonion** [comment]
Hi @Videl , the storage configs must be under the name of storage:
```yaml
    storage_config:
      vault:
        host: myvault
        port: 443
        token: mytoken
        kv_path: mypath
```
